In [1]:
#importing library
from transformers import BertTokenizer, TFBertModel
#defining tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
#instantiating the model
model = TFBertModel.from_pretrained("bert-base-uncased")
text = "What is your name?"
#extracting features
encoded_input = tokenizer(text, return_tensors='tf')
model(encoded_input)

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/511M [00:00<?, ?B/s]

Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['mlm___cls', 'nsp___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(1, 7, 768), dtype=float32, numpy=
array([[[ 0.08028892,  0.15121321, -0.2958817 , ..., -0.25193146,
          0.10468219,  0.46184197],
        [ 0.23416208, -0.01264843, -0.2747215 , ...,  0.17610902,
          0.38892975, -0.2551906 ],
        [ 0.47130805,  0.02673543, -0.17008346, ..., -0.5424892 ,
          0.14111695, -0.23771217],
        ...,
        [ 0.03444475, -0.32429618,  0.07769899, ..., -0.02780228,
          0.08623265, -0.8596272 ],
        [ 0.03843497, -0.07758588, -0.96168417, ..., -0.03568524,
          0.27894577, -0.13651596],
        [ 0.8725083 , -0.02664122, -0.5582643 , ...,  0.03990697,
         -0.62972516, -0.35996273]]], dtype=float32)>, pooler_output=<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-9.12194133e-01, -4.65130001e-01, -7.82819688e-01,
         8.21622789e-01,  3.97013754e-01, -1.70064911e-01,
         9.12612855e-01,  3.89790773e-01, -6.42275691e-0

In [3]:
from transformers import pipeline
model = pipeline('fill-mask', model='bert-base-uncased')
pred = model("he can work as a [MASK].")
pred

All model checkpoint layers were used when initializing TFBertForMaskedLM.

All the layers of TFBertForMaskedLM were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForMaskedLM for predictions without further training.


Downloading:   0%|          | 0.00/455k [00:00<?, ?B/s]

[{'score': 0.05977549031376839,
  'token': 5160,
  'token_str': 'lawyer',
  'sequence': 'he can work as a lawyer.'},
 {'score': 0.04769814386963844,
  'token': 15893,
  'token_str': 'mechanic',
  'sequence': 'he can work as a mechanic.'},
 {'score': 0.034236401319503784,
  'token': 10533,
  'token_str': 'carpenter',
  'sequence': 'he can work as a carpenter.'},
 {'score': 0.02049887366592884,
  'token': 3460,
  'token_str': 'doctor',
  'sequence': 'he can work as a doctor.'},
 {'score': 0.01972660981118679,
  'token': 5268,
  'token_str': 'soldier',
  'sequence': 'he can work as a soldier.'}]

In [14]:
pred = model("what is your [MASK].")
pred[2]['token_str']

'purpose'

In [12]:
import pickle

pickle_file = open('Bert.pkl', 'wb')     
pickle.dump(model, pickle_file)
pickle_file.close()

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Constant'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Constant'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Constant'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set

INFO:tensorflow:Assets written to: ram://ec43337d-514a-4f1f-ae25-79487c715391/assets


INFO:tensorflow:Assets written to: ram://ec43337d-514a-4f1f-ae25-79487c715391/assets
